In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import seaborn as sns

import re

sns.set_style('whitegrid')
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.compose import make_column_transformer, ColumnTransformer
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler, OneHotEncoder

from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, VotingRegressor, StackingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
import lightgbm as lgb

In [2]:
from imblearn.over_sampling import SMOTE

# Dataset Description

## File descriptions

**train.csv** - the training set

**test.csv** - the test set

**data_description.txt** - full description of each column, originally prepared by Dean De Cock but lightly edited to match the column names used here

**sample_submission.csv** - a benchmark submission from a linear regression on year and month of sale, lot square footage, and number of bedrooms

## Data fields

Here's a brief version of what you'll find in the data description file.

- **SalePrice:** the property's sale price in dollars. This is the target variable that you're trying to predict.
- **MSSubClass:** The building class
- **MSZoning:** The general zoning classification
- **LotFrontage:** Linear feet of street connected to property
- **LotArea:** Lot size in square feet
- **Street:** Type of road access
- **Alley:**  Type of alley access
- **LotShape:**  General shape of property
- **LandContour:**  Flatness of the property
- **Utilities:**  Type of utilities available
- **LotConfig:**  Lot configuration
- **LandSlope:**  Slope of property
- **Neighborhood:**  Physical locations within Ames city limits
- **Condition1:**  Proximity to main road or railroad
- **Condition2:**  Proximity to main road or railroad (if a second is present)
- **BldgType:**  Type of dwelling
- **HouseStyle:**  Style of dwelling
- **OverallQual:**  Overall material and finish quality
- **OverallCond:**  Overall condition rating
- **YearBuilt:**  Original construction date
- **YearRemodAdd:**  Remodel date
- **RoofStyle:**  Type of roof
- **RoofMatl:**  Roof material
- **Exterior1st:**  Exterior covering on house
- **Exterior2nd:**  Exterior covering on house (if more than one material)
- **MasVnrType:**  Masonry veneer type
- **MasVnrArea:**  Masonry veneer area in square feet
- **ExterQual:**  Exterior material quality
- **ExterCond:**  Present condition of the material on the exterior
- **Foundation:**  Type of foundation
- **BsmtQual:**  Height of the basement
- **BsmtCond:**  General condition of the basement
- **BsmtExposure:**  Walkout or garden level basement walls
- **BsmtFinType1:**  Quality of basement finished area
- **BsmtFinSF1:**  Type 1 finished square feet
- **BsmtFinType2:**  Quality of second finished area (if present)
- **BsmtFinSF2:**  Type 2 finished square feet
- **BsmtUnfSF:**  Unfinished square feet of basement area
- **TotalBsmtSF:**  Total square feet of basement area
- **Heating:**  Type of heating
- **HeatingQC:**  Heating quality and condition
- **CentralAir:**  Central air conditioning
- **Electrical:**  Electrical system
- **1stFlrSF:**  First Floor square feet
- **2ndFlrSF:**  Second floor square feet
- **LowQualFinSF:**  Low quality finished square feet (all floors)
- **GrLivArea:**  Above grade (ground) living area square feet
- **BsmtFullBath:**  Basement full bathrooms
- **BsmtHalfBath:**  Basement half bathrooms
- **FullBath:**  Full bathrooms above grade
- **HalfBath:**  Half baths above grade
- **Bedroom:**  Number of bedrooms above basement level
- **Kitchen:**  Number of kitchens
- **KitchenQual:**  Kitchen quality
- **TotRmsAbvGrd:**  Total rooms above grade (does not include bathrooms)
- **Functional:**  Home functionality rating
- **Fireplaces:**  Number of fireplaces
- **FireplaceQu:**  Fireplace quality
- **GarageType:**  Garage location
- **GarageYrBlt:**  Year garage was built
- **GarageFinish:**  Interior finish of the garage
- **GarageCars:**  Size of garage in car capacity
- **GarageArea:**  Size of garage in square feet
- **GarageQual:**  Garage quality
- **GarageCond:**  Garage condition
- **PavedDrive:**  Paved driveway
- **WoodDeckSF:**  Wood deck area in square feet
- **OpenPorchSF:**  Open porch area in square feet
- **EnclosedPorch:**  Enclosed porch area in square feet
- **3SsnPorch:**  Three season porch area in square feet
- **ScreenPorch:**  Screen porch area in square feet
- **PoolArea:**  Pool area in square feet
- **PoolQC:**  Pool quality
- **Fence:**  Fence quality
- **MiscFeature:**  Miscellaneous feature not covered in other categories
- **MiscVal:**  $Value of miscellaneous feature
- **MoSold:**  Month Sold
- **YrSold:**  Year Sold
- **SaleType:**  Type of sale
- **SaleCondition:**  Condition of sale

In [3]:
df_train = pd.read_csv("data/competition/train.csv")
df_test = pd.read_csv("data/competition/test.csv")
df_combine = pd.concat([df_train, df_test])#, axis = 1)

In [4]:
df_combine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2919 entries, 0 to 1458
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     1153 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.8+ MB

In [79]:
df_combine.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [103]:
df_combine.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,1460.000000
mean,1460.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,...,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180921.195890
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,...,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,730.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129975.000000
50%,1460.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,2189.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [80]:
df_combine['YrSold'].unique()

array([2008, 2007, 2006, 2009, 2010])

In [100]:
drop_columns = ['LotArea', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'ScreenPorch']
drop_test = ['Alley', 'MasVnrType', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature', 'LotFrontage', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']
df_test = df_combine.drop(drop_columns, axis = 1)
df_test = df_test.drop(drop_test, axis = 1)

In [102]:
for column in df_test.columns:
    if df_test[column].isnull().sum() != 0:
        print(f'{column} : {df_test[column].isnull().sum()}')
len(df_test.columns)

MSZoning : 4
Utilities : 2
Exterior1st : 1
Exterior2nd : 1
Electrical : 1
BsmtFullBath : 2
BsmtHalfBath : 2
KitchenQual : 1
Functional : 2
GarageCars : 1
SaleType : 1
SalePrice : 1459

50